import { readFileSync, writeFileSync } from "node:fs";
const dir = process.argv[2], out = process.argv[3];
const names = ["shield-check","file-search","triangle-alert","circle-help","badge-check","sparkles","message-square-text","external-link","chevron-down","rotate-cw","crosshair","copy","check","circle-alert","globe","app-window"];
let body = "";
for (const n of names) {
  const svg = readFileSync(`${dir}/package/icons/${n}.svg`, "utf8");
  const inner = svg.replace(/^[\s\S]*?>\s*(?=<(?:path|circle|line|rect))/m, "").replace(/<\/svg>\s*$/, "").replace(/\s+/g, " ").trim();
  body += `  ${JSON.stringify(n)}: ${JSON.stringify(inner)},\n`;
}
writeFileSync(out, `// Icons from Lucide (https://lucide.dev), lucide-static v1.49.0, ISC licence. See vendor/LUCIDE-LICENSE.txt.
// Bundled locally; nothing is loaded from a CDN. Generated by scripts/build-icons.mjs from the lucide-static package.
const PATHS = {
${body}};

/** Returns inline SVG markup for a Lucide icon. The markup is static and trusted (never built from page text). */
export function icon(name, size = 16) {
  const inner = PATHS[name];
  if (!inner) throw new Error(\`Unknown icon: \${name}\`);
  return \`<svg class="icon" xmlns="http://www.w3.org/2000/svg" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">\${inner}</svg>\`;
}

export const ICON_NAMES = Object.keys(PATHS);
`);
